Repository hosung77/legend-book, pull requests merged in 2025-05, with the labels that each got.

#7 [#1] feat: 도서 등록 기능 추가
  src/main/java/com/example/praticetokensecurity/domain/book/Controller/AdminBookController.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/AdminBookRequestDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/AdminBookResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/entity/Book.java
  src/main/java/com/example/praticetokensecurity/domain/book/service/AdminBookService.java
Labels: feature

#12 [#11] fix: like 테이블명 수정
  src/main/java/com/example/praticetokensecurity/domain/like/entity/Like.java
Labels: fix

#14 [#5] feat: 등록된 도서 수정 기능 추가
  src/main/java/com/example/praticetokensecurity/common/code/ErrorStatus.java
  src/main/java/com/example/praticetokensecurity/common/code/SuccessStatus.java
  src/main/java/com/example/praticetokensecurity/config/SecurityConfig.java
  src/main/java/com/example/praticetokensecurity/domain/book/Controller/AdminBookController.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/AdminBookUpdateRequestDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/entity/Book.java
  src/main/java/com/example/praticetokensecurity/domain/book/service/AdminBookService.java
Labels: feature

#15 [#6] feat: 등록된 도서 전체 조회
  src/main/java/com/example/praticetokensecurity/common/code/SuccessStatus.java
  src/main/java/com/example/praticetokensecurity/domain/book/Controller/AdminBookController.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/requestDto/AdminBookRequestDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/requestDto/AdminBookUpdateRequestDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/responseDto/AdminBookResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/responseDto/AdminPageResponse.java
  src/main/java/com/example/praticetokensecurity/domain/book/entity/Book.java
  src/main/java/com/example/praticetokensecurity/domain/book/service/AdminBookService.java
Labels: feature

#16 [#13]feat: 좋아요 기능 추가
  src/main/java/com/example/praticetokensecurity/common/code/ErrorStatus.java
  src/main/java/com/example/praticetokensecurity/common/code/SuccessStatus.java
  src/main/java/com/example/praticetokensecurity/domain/like/controller/LikeController.java
  src/main/java/com/example/praticetokensecurity/domain/like/entity/Like.java
  src/main/java/com/example/praticetokensecurity/domain/like/repository/LikeRepository.java
  src/main/java/com/example/praticetokensecurity/domain/like/service/LikeService.java
  src/main/java/com/example/praticetokensecurity/domain/user/entity/User.java
  src/main/resources/application.yaml
Labels: feature

#17 [#10]Feat/book 도서 단 건 조회
  src/main/java/com/example/praticetokensecurity/common/code/ErrorStatus.java
  src/main/java/com/example/praticetokensecurity/common/code/SuccessStatus.java
  src/main/java/com/example/praticetokensecurity/domain/book/Controller/BookController.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/BookResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/enums/BookStatus.java
  src/main/java/com/example/praticetokensecurity/domain/book/enums/Category.java
  src/main/java/com/example/praticetokensecurity/domain/book/repository/BookRepository.java
  src/main/java/com/example/praticetokensecurity/domain/book/service/BookService.java
Labels: feature

#19 [#8] Feat/logout
  src/main/java/com/example/praticetokensecurity/common/code/ErrorStatus.java
  src/main/java/com/example/praticetokensecurity/config/JwtTokenProvider.java
  src/main/java/com/example/praticetokensecurity/config/SecurityConfig.java
  src/main/java/com/example/praticetokensecurity/domain/auth/controller/AuthController.java
  src/main/java/com/example/praticetokensecurity/domain/auth/dto/response/LoginResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/auth/service/AuthService.java
  src/main/java/com/example/praticetokensecurity/domain/user/entity/CustomUserPrincipal.java
Labels: feature

#22 [#20]Feat/search
  src/main/java/com/example/praticetokensecurity/domain/book/Controller/BookController.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/BookResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/responseDto/BookResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/repository/BookRepository.java
  src/main/java/com/example/praticetokensecurity/domain/book/service/BookService.java
  src/main/java/com/example/praticetokensecurity/domain/keyword/Controller/KeywordController.java
  src/main/java/com/example/praticetokensecurity/domain/keyword/entity/Keyword.java
  src/main/java/com/example/praticetokensecurity/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/example/praticetokensecurity/domain/like/service/LikeService.java
Labels: feature

#24 [#23] Feat/logoutv2
  src/main/java/com/example/praticetokensecurity/config/JwtTokenProvider.java
  src/main/java/com/example/praticetokensecurity/domain/auth/controller/AuthController.java
  src/main/java/com/example/praticetokensecurity/domain/auth/service/AuthService.java
  src/main/java/com/example/praticetokensecurity/domain/token/service/RefreshTokenService.java
Labels: fix

#30 [#29] feat: 본인 정보 조회 기능.
  src/main/java/com/example/praticetokensecurity/common/code/ErrorStatus.java
  src/main/java/com/example/praticetokensecurity/common/code/SuccessStatus.java
  src/main/java/com/example/praticetokensecurity/domain/auth/controller/AuthController.java
  src/main/java/com/example/praticetokensecurity/domain/user/controller/UserController.java
  src/main/java/com/example/praticetokensecurity/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/user/service/UserService.java
Labels: feature

#31 [#28] feat: 도서 삭제 기능
  src/main/java/com/example/praticetokensecurity/common/code/SuccessStatus.java
  src/main/java/com/example/praticetokensecurity/domain/book/Controller/AdminBookController.java
  src/main/java/com/example/praticetokensecurity/domain/book/entity/Book.java
  src/main/java/com/example/praticetokensecurity/domain/book/repository/BookRepository.java
  src/main/java/com/example/praticetokensecurity/domain/book/service/AdminBookService.java
Labels: feature

#33 [#27] fix: Status Code 수정
  src/main/java/com/example/praticetokensecurity/common/code/ErrorStatus.java
  src/main/java/com/example/praticetokensecurity/common/code/SuccessStatus.java
Labels: fix

#34 [#32] fix: 등록된 도서 전체 조회 기능
  src/main/java/com/example/praticetokensecurity/domain/book/dto/responseDto/AdminPageResponse.java
  src/main/java/com/example/praticetokensecurity/domain/book/repository/BookRepository.java
  src/main/java/com/example/praticetokensecurity/domain/book/service/AdminBookService.java
Labels: fix

#35 [#18] Feat/book: 도서 대여, 반납 기능, 대여한 도서 목록 기능
  src/main/java/com/example/praticetokensecurity/common/code/ErrorStatus.java
  src/main/java/com/example/praticetokensecurity/common/code/SuccessStatus.java
  src/main/java/com/example/praticetokensecurity/domain/book/Controller/BookController.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/requestDto/BookRentRequestDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/responseDto/RentalResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/dto/responseDto/RentedBookResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/book/entity/Book.java
  src/main/java/com/example/praticetokensecurity/domain/book/repository/BookRepository.java
  src/main/java/com/example/praticetokensecurity/domain/book/service/BookService.java
  src/main/java/com/example/praticetokensecurity/domain/user/controller/UserController.java
  src/main/java/com/example/praticetokensecurity/domain/user/entity/User.java
  src/main/java/com/example/praticetokensecurity/domain/user/service/UserService.java
  src/main/resources/application.yaml
Labels: feature

#36 [#26]Feature/favorite keyword
  build.gradle
  src/main/generated/com/example/praticetokensecurity/common/entity/QTimeStamped.java
  src/main/generated/com/example/praticetokensecurity/domain/book/entity/QBook.java
  src/main/generated/com/example/praticetokensecurity/domain/keyword/entity/QKeyword.java
  src/main/generated/com/example/praticetokensecurity/domain/like/entity/QLike.java
  src/main/generated/com/example/praticetokensecurity/domain/token/entity/QRefreshToken.java
  src/main/generated/com/example/praticetokensecurity/domain/user/entity/QUser.java
  src/main/java/com/example/praticetokensecurity/common/code/SuccessStatus.java
  src/main/java/com/example/praticetokensecurity/config/JPAConfig.java
  src/main/java/com/example/praticetokensecurity/domain/keyword/Controller/KeywordController.java
  src/main/java/com/example/praticetokensecurity/domain/keyword/dto/response/Top5KeywordResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/example/praticetokensecurity/domain/keyword/repository/KeywordRepositoryQuery.java
  src/main/java/com/example/praticetokensecurity/domain/keyword/repository/KeywordRepositoryQueryImpl.java
  src/main/java/com/example/praticetokensecurity/domain/keyword/service/KeywordService.java
  src/main/java/com/example/praticetokensecurity/domain/like/service/LikeService.java
Labels: feature

#38 [#37] Feat/find user
  src/main/java/com/example/praticetokensecurity/common/code/SuccessStatus.java
  src/main/java/com/example/praticetokensecurity/domain/user/controller/UserController.java
  src/main/java/com/example/praticetokensecurity/domain/user/dto/request/UserUpdateRequestDto.java
  src/main/java/com/example/praticetokensecurity/domain/user/entity/User.java
  src/main/java/com/example/praticetokensecurity/domain/user/service/UserService.java
Labels: feature

#40 [#39] feat: 회원 탈퇴 기능 구현
  src/main/generated/com/example/praticetokensecurity/common/entity/QTimeStamped.java
  src/main/generated/com/example/praticetokensecurity/domain/book/entity/QBook.java
  src/main/generated/com/example/praticetokensecurity/domain/keyword/entity/QKeyword.java
  src/main/generated/com/example/praticetokensecurity/domain/like/entity/QLike.java
  src/main/generated/com/example/praticetokensecurity/domain/token/entity/QRefreshToken.java
  src/main/generated/com/example/praticetokensecurity/domain/user/entity/QUser.java
  src/main/java/com/example/praticetokensecurity/domain/book/entity/Book.java
  src/main/java/com/example/praticetokensecurity/domain/book/repository/BookRepository.java
  src/main/java/com/example/praticetokensecurity/domain/user/controller/UserController.java
  src/main/java/com/example/praticetokensecurity/domain/user/dto/request/UserDeleteRequestDto.java
  src/main/java/com/example/praticetokensecurity/domain/user/entity/User.java
  src/main/java/com/example/praticetokensecurity/domain/user/service/UserService.java
Labels: feature

#42 [#41] Feat/like user
  src/main/generated/com/example/praticetokensecurity/common/entity/QTimeStamped.java
  src/main/generated/com/example/praticetokensecurity/domain/book/entity/QBook.java
  src/main/generated/com/example/praticetokensecurity/domain/keyword/entity/QKeyword.java
  src/main/generated/com/example/praticetokensecurity/domain/like/entity/QLike.java
  src/main/generated/com/example/praticetokensecurity/domain/token/entity/QRefreshToken.java
  src/main/generated/com/example/praticetokensecurity/domain/user/entity/QUser.java
  src/main/java/com/example/praticetokensecurity/common/code/SuccessStatus.java
  src/main/java/com/example/praticetokensecurity/domain/like/dto/response/LikedResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/like/repository/LikeRepository.java
  src/main/java/com/example/praticetokensecurity/domain/user/controller/UserController.java
  src/main/java/com/example/praticetokensecurity/domain/user/dto/request/UserDeleteRequestDto.java
  src/main/java/com/example/praticetokensecurity/domain/user/service/UserService.java
Labels: feature

#44 [#43] docs: Admin 기능 주석 추가
  src/main/java/com/example/praticetokensecurity/domain/book/Controller/AdminBookController.java
  src/main/java/com/example/praticetokensecurity/domain/book/service/AdminBookService.java
Labels: docs

#53 [#49] Feat/token reissue
  build.gradle
  src/main/java/com/example/praticetokensecurity/PraticeTokenSecurityApplication.java
  src/main/java/com/example/praticetokensecurity/config/JwtFilter.java
  src/main/java/com/example/praticetokensecurity/config/JwtTokenProvider.java
  src/main/java/com/example/praticetokensecurity/domain/auth/controller/AuthController.java
  src/main/java/com/example/praticetokensecurity/domain/auth/dto/response/LoginResponseDto.java
  src/main/java/com/example/praticetokensecurity/domain/auth/service/AuthService.java
  src/main/java/com/example/praticetokensecurity/domain/token/entity/RefreshToken.java
  src/main/java/com/example/praticetokensecurity/domain/token/repository/RefreshTokenRepository.java
  src/main/java/com/example/praticetokensecurity/domain/token/service/RefreshTokenService.java
  src/main/java/com/example/praticetokensecurity/domain/user/controller/UserController.java
  src/main/java/com/example/praticetokensecurity/domain/user/service/CustomUserDetailsService.java
  src/main/java/com/example/praticetokensecurity/domain/user/service/UserService.java
Labels: feature

#55 [#54] fix: 튜터님 피드백 수정
  src/main/java/com/example/praticetokensecurity/config/JwtTokenProvider.java
  src/main/java/com/example/praticetokensecurity/config/SecurityConfig.java
  src/main/java/com/example/praticetokensecurity/domain/auth/controller/AuthController.java
  src/main/java/com/example/praticetokensecurity/domain/auth/dto/request/LoginRequestDto.java
  src/main/java/com/example/praticetokensecurity/domain/auth/dto/request/SignUpRequestDto.java
  src/main/java/com/example/praticetokensecurity/domain/auth/entity/RefreshToken.java
  src/main/java/com/example/praticetokensecurity/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/example/praticetokensecurity/domain/auth/service/AuthService.java
  src/main/java/com/example/praticetokensecurity/domain/auth/service/RefreshTokenService.java
  src/main/java/com/example/praticetokensecurity/domain/book/controller/AdminBookController.java
  src/main/java/com/example/praticetokensecurity/domain/book/controller/BookController.java
  src/main/java/com/example/praticetokensecurity/domain/book/service/AdminBookService.java
  src/main/java/com/example/praticetokensecurity/domain/keyword/controller/DevKeywordController.java
  src/main/java/com/example/praticetokensecurity/domain/keyword/controller/KeywordController.java
  src/main/java/com/example/praticetokensecurity/domain/token/Controller/TokenController.java
Labels: fix

#59 [#58] fix: secret key 추가
  docker-compose.yaml
Labels: fix

#62 [#61] feat: AdminBookService CRUD 테스트 코드 작성
  src/test/java/com/example/praticetokensecurity/domain/book/service/AdminBookServiceTest.java
Labels: feature, test

#67 [#65] feat: Test/user
  src/test/java/com/example/praticetokensecurity/domain/book/service/BookServiceTest.java
  src/test/java/com/example/praticetokensecurity/domain/user/service/UserServiceTests.java
Labels: feature, test

#69 [#68]refactor: 테스트 메서드 명 변경
  src/test/java/com/example/praticetokensecurity/domain/keyword/service/KeywordServiceTest.java
  src/test/java/com/example/praticetokensecurity/domain/like/service/LikeServiceTest.java
Labels: refactoring

#70 docs: 등록한 모든 도서 조회 리드미 작성
  docs/image/taejeongV1.png
  docs/image/taejeongV2.png
  docs/taejeong.md
Labels: docs

#72 docs: Readme/hyejeong
  docs/hyejeong.md
  docs/image/hyejeongV1.png
  docs/image/hyejeongV2.png
Labels: docs

#73 docs: 인기 검색어 조회 리드미 작성
  docs/hosung.md
  docs/image/hsV1.png
  docs/image/hsV2.png
Labels: docs

#74 fix: readMe 이미지 변경
  docs/hosung.md
  docs/image/hosungV1.png
  docs/image/hosungV2.png
Labels: fix
